name: Translations check

on:
  pull_request:
    branches: [ main ]

jobs:
  validate:
    name: Validate translation files
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Validate translation files
        uses: Tar-Minyatur/gettext-validation@master
        with:
          folder: po/
